<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
MATRIX[0]

tensor([1, 3, 4])

In [12]:
MATRIX[2]

tensor([6, 7, 8])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [14]:
TENSOR.ndim


3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [18]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.2964, 0.6676, 0.0901],
         [0.6615, 0.0573, 0.6429],
         [0.0949, 0.2025, 0.7198],
         [0.1225, 0.9277, 0.1687]],

        [[0.3574, 0.7492, 0.5383],
         [0.8527, 0.2497, 0.5669],
         [0.3889, 0.7956, 0.6994],
         [0.5328, 0.8707, 0.0010]],

        [[0.8695, 0.3911, 0.7567],
         [0.9160, 0.3312, 0.4147],
         [0.0747, 0.5070, 0.4896],
         [0.8587, 0.0906, 0.4190]],

        [[0.8462, 0.0068, 0.2386],
         [0.7577, 0.1098, 0.4420],
         [0.4646, 0.9599, 0.0176],
         [0.5129, 0.5444, 0.0585]],

        [[0.1403, 0.2838, 0.4039],
         [0.7314, 0.1923, 0.7678],
         [0.9441, 0.3958, 0.2159],
         [0.4108, 0.9141, 0.0797]]])

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.8838, 0.7976, 0.3830],
         [0.7274, 0.4768, 0.6447],
         [0.2448, 0.8020, 0.9194],
         ...,
         [0.7363, 0.9831, 0.2872],
         [0.4419, 0.2824, 0.7859],
         [0.8338, 0.1041, 0.3791]],

        [[0.6012, 0.8372, 0.3421],
         [0.5002, 0.7025, 0.2113],
         [0.7869, 0.0186, 0.5010],
         ...,
         [0.5055, 0.7027, 0.3931],
         [0.8513, 0.5229, 0.7272],
         [0.5679, 0.9180, 0.8244]],

        [[0.2911, 0.0340, 0.6798],
         [0.8157, 0.4773, 0.4222],
         [0.5224, 0.1507, 0.0952],
         ...,
         [0.4080, 0.4315, 0.0634],
         [0.1702, 0.3071, 0.6862],
         [0.1132, 0.5332, 0.4731]],

        ...,

        [[0.6776, 0.2090, 0.0105],
         [0.5701, 0.4828, 0.0451],
         [0.4565, 0.2963, 0.8557],
         ...,
         [0.2481, 0.0190, 0.9732],
         [0.6745, 0.5215, 0.2488],
         [0.3103, 0.4949, 0.0172]],

        [[0.9749, 0.2809, 0.4803],
         [0.4635, 0.4524, 0.8769],
         [0.

In [20]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [24]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [25]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [26]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
some_tensor = torch.rand(size=(3,4),dtype=torch.float16)
some_tensor

tensor([[0.4404, 0.6357, 0.8564, 0.1191],
        [0.1997, 0.4272, 0.0913, 0.3394],
        [0.3750, 0.1367, 0.1689, 0.4722]], dtype=torch.float16)

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.4404, 0.6357, 0.8564, 0.1191],
        [0.1997, 0.4272, 0.0913, 0.3394],
        [0.3750, 0.1367, 0.1689, 0.4722]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [29]:
#Manipulation of Tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [30]:
tensor*10


tensor([10, 20, 30])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [33]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [34]:
#Element wise Multipllication
print(tensor,'*',tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
## Matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 896 µs, sys: 0 ns, total: 896 µs
Wall time: 15.9 ms


tensor(14)

In [36]:
## Mulipliction by hand
%%time
value =0
for ele in tensor:
 value+=ele*ele
print(value)

tensor(14)
CPU times: user 571 µs, sys: 1.1 ms, total: 1.67 ms
Wall time: 2.93 ms


In [37]:
MATRIX1 = torch.tensor([[2,3,5],
                        [5,6,7],
                        [9,2,4]])

In [38]:
MATRIX2 = torch.tensor([[9,5,6],
                        [5,3,4],
                        [2,5,6]])

In [39]:
torch.matmul(MATRIX2,MATRIX1)

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [40]:
MATRIX2 @ MATRIX1

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [41]:
torch.matmul(torch.rand(1,3),torch.rand(3,5))

tensor([[0.6035, 0.9577, 0.2888, 0.7582, 1.0851]])

In [42]:
tensor_1= torch.tensor([[1,2],
                        [4,5],
                        [7,8]])

In [43]:
tensor_2 = torch.tensor([[10,11],
                         [12,13],
                         [14,15]])

In [44]:
tensor_1.shape ,tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [45]:
torch.matmul(tensor_1,tensor_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
transpose_of_tensor_2 =tensor_2.T
transpose_of_tensor_2

tensor([[10, 12, 14],
        [11, 13, 15]])

In [47]:
transpose_of_tensor_2.shape

torch.Size([2, 3])

In [48]:
torch.matmul(tensor_1,transpose_of_tensor_2)

tensor([[ 32,  38,  44],
        [ 95, 113, 131],
        [158, 188, 218]])

In [49]:
## Here shape of the tensor 1 and 2 are (3,2) and (3,2)
## We Know for multiplication of two matrix of shape (m,n)and (p,q) n=p and the
##Output matrix will be shape (m,q)

In [50]:
print(f"Shape of the tensor_1: {tensor_1.shape} and tensor_2: {tensor_2.shape}")
print(f"Shape of the tensor_1: {tensor_1.shape} and shape of the tensor_2 transpose matrix is : {transpose_of_tensor_2.shape}")
print(f"Shape of the output tensor: {torch.matmul(tensor_1,transpose_of_tensor_2).shape}")


Shape of the tensor_1: torch.Size([3, 2]) and tensor_2: torch.Size([3, 2])
Shape of the tensor_1: torch.Size([3, 2]) and shape of the tensor_2 transpose matrix is : torch.Size([2, 3])
Shape of the output tensor: torch.Size([3, 3])


In [51]:
## Find the min,Max,Sum etc tensor aggregation
x = torch.arange(1 , 100 ,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [52]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [53]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [54]:
## the torch.mean function required a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [55]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
#find the min or max values index position
x.argmin()

tensor(0)

In [57]:
x.argmax()

tensor(9)

**Reshape ,View , Stacking , Squeeze,Unsqueeze, Permute**

In [58]:
#Reshape
x = torch.arange(1.0 , 10.0)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
x.ndim

1

In [60]:
# Reshape add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_reshaped.ndim

2

In [62]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
x_reshaped.ndim

2

In [64]:
#Change the view
z = x.view(1,9)
z ,z.shape,z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [65]:
#Changing  z changes x because they shares the same memory
z[:,0] = 10
z,x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [66]:
# Stack tensor on top of each others
x_stacked = torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [67]:
y = torch.arange(10,19)

In [68]:
xy_stacked = torch.stack([x,y,x,y,x],dim=1)
xy_stacked

tensor([[10., 10., 10., 10., 10.],
        [ 2., 11.,  2., 11.,  2.],
        [ 3., 12.,  3., 12.,  3.],
        [ 4., 13.,  4., 13.,  4.],
        [ 5., 14.,  5., 14.,  5.],
        [ 6., 15.,  6., 15.,  6.],
        [ 7., 16.,  7., 16.,  7.],
        [ 8., 17.,  8., 17.,  8.],
        [ 9., 18.,  9., 18.,  9.]])

In [69]:
#torch.squeez remove  all single dimension from a tsrget tensor
k = torch.arange(1,11)
k_reshape = k.reshape(1,10)
k_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [70]:
k_reshape.shape

torch.Size([1, 10])

In [71]:
k_squeeze = k_reshape.squeeze()

In [72]:
k_squeeze.shape ,k_reshape.shape

(torch.Size([10]), torch.Size([1, 10]))

In [73]:
#torch.unzqueeze add a singel dimension
k_unsqueezed = k_squeeze.unsqueeze(dim=0)
k_unsqueezed.shape

torch.Size([1, 10])

In [74]:
##### torch.permute Rearrange the dimension of a target tensor in a specified order
image = torch.rand(size=(224,224,3)) # [height , width , color channel]
image.shape

torch.Size([224, 224, 3])

In [75]:
img_premuted = image.permute(2,0,1) #shifta axis 0->1 , 1->2 ,2->0 [color channel , height, width]

In [76]:
print(f"Original shape: {image.shape}")
print(f"Permuted shape: {img_premuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [77]:
#Selecting data or Tensor with indexing
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [78]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0][0]

tensor([1, 2, 3])

In [80]:
x[0][0][0]

tensor(1)

In [81]:
x[0][1][2]

tensor(6)

In [82]:
x[:,0]

tensor([[1, 2, 3]])

In [83]:
x[:,:, 0]

tensor([[1, 4, 7]])

In [84]:
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
x[:,:,2]

tensor([[3, 6, 9]])

In [86]:
x[:,1,1]

tensor([5])

In [87]:
x[:,2,1]

tensor([8])

In [88]:
x[0,0,:],x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [89]:
x[:,:,2]

tensor([[3, 6, 9]])

In [90]:
## pytorch tensor and Numpy
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [91]:
array.dtype ,tensor.dtype

(dtype('float64'), torch.float64)

In [92]:
tensor.type(torch.float32).dtype

torch.float32

In [93]:
## chage value of array
array = array+1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [94]:
## Tensor to numpy
tensor1 = torch.ones(7)
tensor1

tensor([1., 1., 1., 1., 1., 1., 1.])

In [95]:
numpy_tensor = tensor1.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [96]:
tensor1.dtype , numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [97]:
## Rreproducbility (Trying to take random out of random )
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3107, 0.8126, 0.4780, 0.9640],
        [0.6474, 0.7262, 0.0248, 0.4134],
        [0.2040, 0.5548, 0.3439, 0.6361]])
tensor([[0.9337, 0.9423, 0.3252, 0.7636],
        [0.9254, 0.2359, 0.4456, 0.0308],
        [0.3340, 0.0458, 0.2562, 0.6513]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [98]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [100]:
### Running tensor and pytorch in GPU

!nvidia-smi

Wed Nov 19 12:01:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   55C    P8             11W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [103]:
torch.cuda.is_available()

True

In [105]:
##setup device agnostic code

if torch.cuda.is_available():
  device ="cuda"
else:
 device = "cpu"
print(f"Used device is {device}")

Used device is cuda


In [108]:
torch.cuda.device_count()

1

In [126]:
%%time
##Crate a tensor
tensor = torch.tensor([1,2,3],device="cpu")
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu
CPU times: user 896 µs, sys: 0 ns, total: 896 µs
Wall time: 735 µs


In [127]:
%%time
## tensor on GPU
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


CPU times: user 787 µs, sys: 52 µs, total: 839 µs
Wall time: 610 µs


tensor([1, 2, 3], device='cuda:0')

In [129]:
## WE can't run numpy in GPU so we need to move from GPU to CPU
tensor_on_gpu.cpu().numpy()


array([1, 2, 3])

## 1. Create a random tensor with shape (7, 7)

In [132]:
tensor = torch.rand(7,7)
tensor

tensor([[0.9998, 0.5944, 0.6541, 0.0337, 0.1716, 0.3336, 0.5782],
        [0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654, 0.1612],
        [0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008, 0.9302],
        [0.6558, 0.0766, 0.8460, 0.3624, 0.3083, 0.0850, 0.0029],
        [0.6431, 0.3908, 0.6947, 0.0897, 0.8712, 0.1330, 0.4137],
        [0.6044, 0.7581, 0.9037, 0.9555, 0.1035, 0.6258, 0.2849],
        [0.4452, 0.1258, 0.9554, 0.1330, 0.7672, 0.6757, 0.6625]])

## 2. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).


In [134]:
tensor_A = torch.rand(size=(1,7))
tensor_A

tensor([[0.2709, 0.9295, 0.6115, 0.2234, 0.2469, 0.4761, 0.7792]])

In [142]:
tensor_A_trans =torch.transpose(tensor_A,0,1)
tensor_A_trans

tensor([[0.2709],
        [0.9295],
        [0.6115],
        [0.2234],
        [0.2469],
        [0.4761],
        [0.7792]])

In [143]:
torch.matmul(tensor ,tensor_A_trans)

tensor([[1.8826],
        [0.9401],
        [1.6033],
        [0.9660],
        [1.5830],
        [2.1800],
        [1.8788]])

In [150]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
tensor_A = torch.rand(7,7)
torch.manual_seed(RANDOM_SEED)
tensor_B = torch.rand(7,1)

tensor_A , tensor_B ,torch.matmul(tensor_A,tensor_B)


(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]),
 tensor([[0.8823],
         [0.9150],
         [0.3829],
         [0.9593],
         [0.3904],
         [0.6009],
         [0.2566]]),
 tensor([[3.2618],
         [3.4084],
         [2.4866],
         [1.4525],
         [1.7079],
         [2.7291],
         [2.9204]]))

## 3.  Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)


In [151]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)

##4. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [177]:
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(2,3,device=device)
torch.cuda.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(2,3,device=device)
tensor_C ,tensor_D ,tensor_C == tensor_D

(tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[0.1272, 0.8167, 0.5440],
         [0.6601, 0.2721, 0.9737]], device='cuda:0'),
 tensor([[True, True, True],
         [True, True, True]], device='cuda:0'))

## 5.  Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [172]:
tensor_D_trans = tensor_D.T
tensor_C.shape , tensor_D_trans.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [189]:
%%time
mul_ten =torch.matmul(tensor_C,tensor_D_trans)
mul_ten

CPU times: user 411 µs, sys: 20 µs, total: 431 µs
Wall time: 266 µs


tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')

In [169]:
mul_ten.max()

tensor(1.4578, device='cuda:0')

In [170]:
mul_ten.min()

tensor(0.8358, device='cuda:0')

In [178]:
mul_ten.argmax() ,mul_ten.argmin()

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

## 6.  Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [192]:
torch.manual_seed(7)
tensor_E = torch.rand(size =(1,1,1,10))

tensor_F = tensor_E.squeeze()

In [194]:
tensor_E ,tensor_F

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))

In [193]:
tensor_E.shape , tensor_F.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))