<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
MATRIX[0]

tensor([1, 3, 4])

In [12]:
MATRIX[2]

tensor([6, 7, 8])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [14]:
TENSOR.ndim


3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [18]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.8036, 0.2569, 0.0539],
         [0.0205, 0.4616, 0.9845],
         [0.6118, 0.4190, 0.4239],
         [0.1174, 0.0239, 0.0579]],

        [[0.8163, 0.4631, 0.3966],
         [0.8576, 0.2702, 0.1760],
         [0.5051, 0.7389, 0.2749],
         [0.7458, 0.5155, 0.4903]],

        [[0.3764, 0.2331, 0.4115],
         [0.3496, 0.2648, 0.5247],
         [0.5945, 0.4144, 0.3252],
         [0.8117, 0.5318, 0.2061]],

        [[0.1217, 0.2814, 0.8947],
         [0.8600, 0.1015, 0.0562],
         [0.0543, 0.8302, 0.3928],
         [0.3049, 0.5067, 0.4611]],

        [[0.2959, 0.4719, 0.9664],
         [0.4866, 0.6490, 0.2007],
         [0.0889, 0.1840, 0.6835],
         [0.2338, 0.0012, 0.9975]]])

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.8747, 0.7411, 0.4971],
         [0.5909, 0.7947, 0.7121],
         [0.9711, 0.8595, 0.5695],
         ...,
         [0.7342, 0.4961, 0.0903],
         [0.1357, 0.7009, 0.9362],
         [0.0065, 0.5354, 0.9441]],

        [[0.8849, 0.6055, 0.4134],
         [0.0179, 0.2850, 0.7149],
         [0.8166, 0.3968, 0.3098],
         ...,
         [0.8802, 0.3698, 0.9499],
         [0.9204, 0.5903, 0.2135],
         [0.6666, 0.2301, 0.0655]],

        [[0.7467, 0.4407, 0.4335],
         [0.3906, 0.6104, 0.6226],
         [0.1340, 0.8085, 0.8737],
         ...,
         [0.7734, 0.8840, 0.9983],
         [0.7982, 0.8628, 0.8029],
         [0.8154, 0.4550, 0.3736]],

        ...,

        [[0.7802, 0.3784, 0.6234],
         [0.2061, 0.7655, 0.9421],
         [0.3624, 0.8039, 0.0937],
         ...,
         [0.6543, 0.5239, 0.7484],
         [0.1842, 0.9449, 0.9189],
         [0.1823, 0.2436, 0.8107]],

        [[0.1476, 0.3839, 0.7961],
         [0.6868, 0.5931, 0.4391],
         [0.

In [20]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [24]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [25]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [26]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
some_tensor = torch.rand(size=(3,4),dtype=torch.float16)
some_tensor

tensor([[0.6484, 0.5430, 0.9736, 0.1577],
        [0.6938, 0.4326, 0.3887, 0.2710],
        [0.5342, 0.5146, 0.5874, 0.8110]], dtype=torch.float16)

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.6484, 0.5430, 0.9736, 0.1577],
        [0.6938, 0.4326, 0.3887, 0.2710],
        [0.5342, 0.5146, 0.5874, 0.8110]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [29]:
#Manipulation of Tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [30]:
tensor*10


tensor([10, 20, 30])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [33]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [34]:
#Element wise Multipllication
print(tensor,'*',tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
## Matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 1.35 ms, sys: 0 ns, total: 1.35 ms
Wall time: 15 ms


tensor(14)

In [36]:
## Mulipliction by hand
%%time
value =0
for ele in tensor:
 value+=ele*ele
print(value)

tensor(14)
CPU times: user 616 µs, sys: 611 µs, total: 1.23 ms
Wall time: 1.25 ms


In [37]:
MATRIX1 = torch.tensor([[2,3,5],
                        [5,6,7],
                        [9,2,4]])

In [38]:
MATRIX2 = torch.tensor([[9,5,6],
                        [5,3,4],
                        [2,5,6]])

In [39]:
torch.matmul(MATRIX2,MATRIX1)

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [40]:
MATRIX2 @ MATRIX1

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [41]:
torch.matmul(torch.rand(1,3),torch.rand(3,5))

tensor([[1.7865, 0.6253, 1.6692, 1.0994, 1.0569]])

In [43]:
tensor_1= torch.tensor([[1,2],
                        [4,5],
                        [7,8]])

In [42]:
tensor_2 = torch.tensor([[10,11],
                         [12,13],
                         [14,15]])

In [44]:
tensor_1.shape ,tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [45]:
torch.matmul(tensor_1,tensor_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [49]:
transpose_of_tensor_2 =tensor_2.T
transpose_of_tensor_2

tensor([[10, 12, 14],
        [11, 13, 15]])

In [50]:
transpose_of_tensor_2.shape

torch.Size([2, 3])

In [51]:
torch.matmul(tensor_1,transpose_of_tensor_2)

tensor([[ 32,  38,  44],
        [ 95, 113, 131],
        [158, 188, 218]])

In [ ]:
## Here shape of the tensor 1 and 2 are (3,2) and (3,2)
## We Know for multiplication of two matrix of shape (m,n)and (p,q) n=p and the
##Output matrix will be shape (m,q)

In [52]:
print(f"Shape of the tensor_1: {tensor_1.shape} and tensor_2: {tensor_2.shape}")
print(f"Shape of the tensor_1: {tensor_1.shape} and shape of the tensor_2 transpose matrix is : {transpose_of_tensor_2.shape}")
print(f"Shape of the output tensor: {torch.matmul(tensor_1,transpose_of_tensor_2).shape}")


Shape of the tensor_1: torch.Size([3, 2]) and tensor_2: torch.Size([3, 2])
Shape of the tensor_1: torch.Size([3, 2]) and shape of the tensor_2 transpose matrix is : torch.Size([2, 3])
Shape of the output tensor: torch.Size([3, 3])
