<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
MATRIX[0]

tensor([1, 3, 4])

In [12]:
MATRIX[2]

tensor([6, 7, 8])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [14]:
TENSOR.ndim


3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [18]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.6336, 0.4663, 0.1905],
         [0.0410, 0.0833, 0.1815],
         [0.0616, 0.2460, 0.6551],
         [0.3555, 0.8824, 0.8580]],

        [[0.6285, 0.9947, 0.3745],
         [0.8434, 0.6100, 0.5180],
         [0.8856, 0.8043, 0.7628],
         [0.5114, 0.7209, 0.0331]],

        [[0.9413, 0.2613, 0.6275],
         [0.6834, 0.9785, 0.8046],
         [0.8905, 0.5154, 0.8864],
         [0.4281, 0.7235, 0.7063]],

        [[0.2410, 0.9161, 0.5046],
         [0.8215, 0.6050, 0.4971],
         [0.9570, 0.0569, 0.3186],
         [0.2259, 0.1462, 0.1278]],

        [[0.6260, 0.4326, 0.0396],
         [0.9224, 0.5678, 0.0765],
         [0.8009, 0.0071, 0.7172],
         [0.5871, 0.1873, 0.4385]]])

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.9836, 0.8744, 0.0105],
         [0.6059, 0.9063, 0.6957],
         [0.8339, 0.6131, 0.4530],
         ...,
         [0.5307, 0.0653, 0.4924],
         [0.0116, 0.5353, 0.9870],
         [0.8295, 0.6578, 0.2431]],

        [[0.1045, 0.0489, 0.7295],
         [0.7591, 0.0604, 0.8011],
         [0.2736, 0.7395, 0.4947],
         ...,
         [0.0134, 0.8937, 0.2963],
         [0.2292, 0.4716, 0.0768],
         [0.7928, 0.5254, 0.1364]],

        [[0.3957, 0.9869, 0.0346],
         [0.1195, 0.1634, 0.2866],
         [0.7449, 0.1104, 0.0209],
         ...,
         [0.6862, 0.0024, 0.1032],
         [0.6685, 0.7213, 0.7710],
         [0.0563, 0.8381, 0.2688]],

        ...,

        [[0.4258, 0.5626, 0.8251],
         [0.6528, 0.9683, 0.3492],
         [0.2323, 0.8724, 0.5877],
         ...,
         [0.8570, 0.4074, 0.7826],
         [0.9870, 0.3726, 0.6008],
         [0.4118, 0.5443, 0.3057]],

        [[0.9952, 0.2087, 0.2545],
         [0.6276, 0.1536, 0.8028],
         [0.

In [20]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [24]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [25]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [26]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
some_tensor = torch.rand(size=(3,4),dtype=torch.float16)
some_tensor

tensor([[0.9111, 0.7900, 0.3301, 0.7402],
        [0.6870, 0.2900, 0.2046, 0.9556],
        [0.8940, 0.2402, 0.1929, 0.7397]], dtype=torch.float16)

In [28]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9111, 0.7900, 0.3301, 0.7402],
        [0.6870, 0.2900, 0.2046, 0.9556],
        [0.8940, 0.2402, 0.1929, 0.7397]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [29]:
#Manipulation of Tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [30]:
tensor*10


tensor([10, 20, 30])

In [31]:
tensor-10

tensor([-9, -8, -7])

In [32]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [33]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [34]:
#Element wise Multipllication
print(tensor,'*',tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [35]:
## Matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 854 µs, sys: 0 ns, total: 854 µs
Wall time: 13.9 ms


tensor(14)

In [36]:
## Mulipliction by hand
%%time
value =0
for ele in tensor:
 value+=ele*ele
print(value)

tensor(14)
CPU times: user 1.37 ms, sys: 0 ns, total: 1.37 ms
Wall time: 1.45 ms


In [37]:
MATRIX1 = torch.tensor([[2,3,5],
                        [5,6,7],
                        [9,2,4]])

In [38]:
MATRIX2 = torch.tensor([[9,5,6],
                        [5,3,4],
                        [2,5,6]])

In [39]:
torch.matmul(MATRIX2,MATRIX1)

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [40]:
MATRIX2 @ MATRIX1

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [41]:
torch.matmul(torch.rand(1,3),torch.rand(3,5))

tensor([[0.8060, 0.6232, 0.6820, 0.5228, 0.8390]])

In [42]:
tensor_1= torch.tensor([[1,2],
                        [4,5],
                        [7,8]])

In [43]:
tensor_2 = torch.tensor([[10,11],
                         [12,13],
                         [14,15]])

In [44]:
tensor_1.shape ,tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [45]:
torch.matmul(tensor_1,tensor_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [46]:
transpose_of_tensor_2 =tensor_2.T
transpose_of_tensor_2

tensor([[10, 12, 14],
        [11, 13, 15]])

In [47]:
transpose_of_tensor_2.shape

torch.Size([2, 3])

In [48]:
torch.matmul(tensor_1,transpose_of_tensor_2)

tensor([[ 32,  38,  44],
        [ 95, 113, 131],
        [158, 188, 218]])

In [49]:
## Here shape of the tensor 1 and 2 are (3,2) and (3,2)
## We Know for multiplication of two matrix of shape (m,n)and (p,q) n=p and the
##Output matrix will be shape (m,q)

In [50]:
print(f"Shape of the tensor_1: {tensor_1.shape} and tensor_2: {tensor_2.shape}")
print(f"Shape of the tensor_1: {tensor_1.shape} and shape of the tensor_2 transpose matrix is : {transpose_of_tensor_2.shape}")
print(f"Shape of the output tensor: {torch.matmul(tensor_1,transpose_of_tensor_2).shape}")


Shape of the tensor_1: torch.Size([3, 2]) and tensor_2: torch.Size([3, 2])
Shape of the tensor_1: torch.Size([3, 2]) and shape of the tensor_2 transpose matrix is : torch.Size([2, 3])
Shape of the output tensor: torch.Size([3, 3])


In [51]:
## Find the min,Max,Sum etc tensor aggregation
x = torch.arange(1 , 100 ,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [52]:
torch.min(x) , x.min()

(tensor(1), tensor(1))

In [53]:
torch.max(x) , x.max()

(tensor(91), tensor(91))

In [54]:
## the torch.mean function required a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [55]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [56]:
#find the min or max values index position
x.argmin()

tensor(0)

In [57]:
x.argmax()

tensor(9)

**Reshape ,View , Stacking , Squeeze,Unsqueeze, Permute**

In [58]:
#Reshape
x = torch.arange(1.0 , 10.0)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [59]:
x.ndim

1

In [60]:
# Reshape add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [61]:
x_reshaped.ndim

2

In [62]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [63]:
x_reshaped.ndim

2

In [64]:
#Change the view
z = x.view(1,9)
z ,z.shape,z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [65]:
#Changing  z changes x because they shares the same memory
z[:,0] = 10
z,x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [66]:
# Stack tensor on top of each others
x_stacked = torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [67]:
y = torch.arange(10,19)

In [68]:
xy_stacked = torch.stack([x,y,x,y,x],dim=1)
xy_stacked

tensor([[10., 10., 10., 10., 10.],
        [ 2., 11.,  2., 11.,  2.],
        [ 3., 12.,  3., 12.,  3.],
        [ 4., 13.,  4., 13.,  4.],
        [ 5., 14.,  5., 14.,  5.],
        [ 6., 15.,  6., 15.,  6.],
        [ 7., 16.,  7., 16.,  7.],
        [ 8., 17.,  8., 17.,  8.],
        [ 9., 18.,  9., 18.,  9.]])

In [69]:
#torch.squeez remove  all single dimension from a tsrget tensor
k = torch.arange(1,11)
k_reshape = k.reshape(1,10)
k_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [70]:
k_reshape.shape

torch.Size([1, 10])

In [71]:
k_squeeze = k_reshape.squeeze()

In [72]:
k_squeeze.shape ,k_reshape.shape

(torch.Size([10]), torch.Size([1, 10]))

In [73]:
#torch.unzqueeze add a singel dimension
k_unsqueezed = k_squeeze.unsqueeze(dim=0)
k_unsqueezed.shape

torch.Size([1, 10])

In [74]:
##### torch.permute Rearrange the dimension of a target tensor in a specified order
image = torch.rand(size=(224,224,3)) # [height , width , color channel]
image.shape

torch.Size([224, 224, 3])

In [75]:
img_premuted = image.permute(2,0,1) #shifta axis 0->1 , 1->2 ,2->0 [color channel , height, width]

In [76]:
print(f"Original shape: {image.shape}")
print(f"Permuted shape: {img_premuted.shape}")

Original shape: torch.Size([224, 224, 3])
Permuted shape: torch.Size([3, 224, 224])


In [77]:
#Selecting data or Tensor with indexing
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [78]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [79]:
x[0][0]

tensor([1, 2, 3])

In [80]:
x[0][0][0]

tensor(1)

In [81]:
x[0][1][2]

tensor(6)

In [82]:
x[:,0]

tensor([[1, 2, 3]])

In [83]:
x[:,:, 0]

tensor([[1, 4, 7]])

In [84]:
x[:,:,1]

tensor([[2, 5, 8]])

In [85]:
x[:,:,2]

tensor([[3, 6, 9]])

In [86]:
x[:,1,1]

tensor([5])

In [87]:
x[:,2,1]

tensor([8])

In [88]:
x[0,0,:],x[0][0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [89]:
x[:,:,2]

tensor([[3, 6, 9]])

In [92]:
## pytorch tensor and Numpy
import numpy as np
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [101]:
array.dtype ,tensor.dtype

(dtype('float64'), torch.float64)

In [102]:
tensor.type(torch.float32).dtype

torch.float32

In [103]:
## chage value of array
array = array+1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [110]:
## Tensor to numpy
tensor1 = torch.ones(7)
tensor1

tensor([1., 1., 1., 1., 1., 1., 1.])

In [111]:
numpy_tensor = tensor1.numpy()
numpy_tensor

array([1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [114]:
tensor1.dtype , numpy_tensor.dtype

(torch.float32, dtype('float32'))