<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [11]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [6]:
scaler.ndim

0

In [12]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [13]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([3])

In [17]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [18]:
MATRIX.ndim

2

In [19]:
MATRIX.shape

torch.Size([3, 3])

In [20]:
MATRIX[0]

tensor([1, 3, 4])

In [22]:
MATRIX[2]

tensor([6, 7, 8])

In [28]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [25]:
TENSOR.ndim


3

In [29]:
TENSOR.shape

torch.Size([2, 3, 3])

In [30]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [31]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [39]:
#Create a random tensor
random_tensor = torch.rand(3,4,3)
random_tensor

tensor([[[0.4028, 0.1739, 0.1141],
         [0.7117, 0.2804, 0.7725],
         [0.5583, 0.4147, 0.6139],
         [0.0708, 0.7836, 0.4775]],

        [[0.4884, 0.0046, 0.3194],
         [0.6010, 0.6622, 0.6965],
         [0.7185, 0.2387, 0.6526],
         [0.9209, 0.3249, 0.2585]],

        [[0.5046, 0.4534, 0.8052],
         [0.5248, 0.6372, 0.2027],
         [0.8982, 0.4501, 0.0422],
         [0.9648, 0.9901, 0.1040]]])