<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [4]:
scaler.ndim

0

In [5]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([3])

In [8]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([3, 3])

In [11]:
MATRIX[0]

tensor([1, 3, 4])

In [12]:
MATRIX[2]

tensor([6, 7, 8])

In [13]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [14]:
TENSOR.ndim


3

In [15]:
TENSOR.shape

torch.Size([2, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [18]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.5837, 0.7072, 0.9186],
         [0.5989, 0.5466, 0.4313],
         [0.0025, 0.5336, 0.2645],
         [0.4650, 0.4138, 0.7389]],

        [[0.1647, 0.6701, 0.9933],
         [0.6724, 0.2672, 0.3945],
         [0.6460, 0.0943, 0.7640],
         [0.6140, 0.6577, 0.8020]],

        [[0.0636, 0.8382, 0.9321],
         [0.7518, 0.3936, 0.8085],
         [0.0832, 0.9266, 0.1938],
         [0.0213, 0.5660, 0.0979]],

        [[0.3460, 0.0409, 0.0385],
         [0.4055, 0.6451, 0.9742],
         [0.0027, 0.6324, 0.4531],
         [0.0971, 0.8653, 0.1108]],

        [[0.7402, 0.3994, 0.6921],
         [0.7874, 0.5139, 0.7202],
         [0.7053, 0.0801, 0.1827],
         [0.7609, 0.5664, 0.8300]]])

In [19]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.0768, 0.8372, 0.6165],
         [0.5781, 0.7767, 0.3265],
         [0.7119, 0.4087, 0.1561],
         ...,
         [0.8493, 0.8368, 0.5992],
         [0.9260, 0.1397, 0.6722],
         [0.6230, 0.3670, 0.9838]],

        [[0.3593, 0.2369, 0.3408],
         [0.3934, 0.2228, 0.3184],
         [0.1695, 0.4921, 0.7767],
         ...,
         [0.2653, 0.1530, 0.9320],
         [0.1768, 0.0073, 0.5631],
         [0.5070, 0.9425, 0.0842]],

        [[0.3167, 0.9913, 0.6084],
         [0.3664, 0.4909, 0.1689],
         [0.3499, 0.2995, 0.3755],
         ...,
         [0.8449, 0.3346, 0.5951],
         [0.3766, 0.2691, 0.7397],
         [0.7853, 0.3061, 0.3400]],

        ...,

        [[0.5761, 0.6925, 0.8922],
         [0.6236, 0.5763, 0.7150],
         [0.5395, 0.4315, 0.4870],
         ...,
         [0.6981, 0.5027, 0.4465],
         [0.6329, 0.1579, 0.9592],
         [0.8897, 0.6624, 0.1675]],

        [[0.5913, 0.9781, 0.0283],
         [0.1077, 0.5176, 0.2172],
         [0.

In [20]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [24]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [25]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [26]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
some_tensor = torch.rand(size=(3,4),dtype=torch.float16)
some_tensor

tensor([[0.1685, 0.2373, 0.2446, 0.9062],
        [0.4204, 0.7769, 0.0522, 0.1270],
        [0.3877, 0.6284, 0.7979, 0.5439]], dtype=torch.float16)

In [31]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1685, 0.2373, 0.2446, 0.9062],
        [0.4204, 0.7769, 0.0522, 0.1270],
        [0.3877, 0.6284, 0.7979, 0.5439]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [44]:
#Manipulation of Tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [47]:
tensor*10


tensor([10, 20, 30])

In [48]:
tensor-10

tensor([-9, -8, -7])

In [49]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [51]:
torch.mul(tensor,20)

tensor([20, 40, 60])