<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [47]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [48]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [49]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [50]:
scaler.ndim

0

In [51]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [52]:
vector.ndim

1

In [53]:
vector.shape

torch.Size([3])

In [54]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [55]:
MATRIX.ndim

2

In [56]:
MATRIX.shape

torch.Size([3, 3])

In [57]:
MATRIX[0]

tensor([1, 3, 4])

In [58]:
MATRIX[2]

tensor([6, 7, 8])

In [59]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [60]:
TENSOR.ndim


3

In [61]:
TENSOR.shape

torch.Size([2, 3, 3])

In [62]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [63]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [64]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.3633, 0.0427, 0.5350],
         [0.1085, 0.5923, 0.8974],
         [0.7953, 0.7936, 0.8259],
         [0.4070, 0.9753, 0.5175]],

        [[0.1216, 0.5326, 0.9565],
         [0.2748, 0.7260, 0.7005],
         [0.8685, 0.3008, 0.2578],
         [0.6335, 0.3341, 0.7019]],

        [[0.6989, 0.8635, 0.2954],
         [0.8700, 0.1264, 0.7878],
         [0.5046, 0.1757, 0.0614],
         [0.2877, 0.1695, 0.9111]],

        [[0.5203, 0.6425, 0.5092],
         [0.9961, 0.9168, 0.6045],
         [0.9924, 0.1044, 0.0824],
         [0.6186, 0.1006, 0.6661]],

        [[0.6854, 0.5607, 0.2848],
         [0.3561, 0.3506, 0.2377],
         [0.4043, 0.3634, 0.0601],
         [0.1362, 0.6395, 0.2997]]])

In [65]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.9175, 0.6679, 0.4952],
         [0.8083, 0.9964, 0.7359],
         [0.2708, 0.6281, 0.8213],
         ...,
         [0.8926, 0.1000, 0.4172],
         [0.5840, 0.3891, 0.8675],
         [0.8886, 0.1352, 0.2038]],

        [[0.2375, 0.9803, 0.3095],
         [0.0744, 0.5997, 0.5143],
         [0.4424, 0.2022, 0.8962],
         ...,
         [0.9554, 0.3043, 0.7716],
         [0.7957, 0.6895, 0.1696],
         [0.2064, 0.0443, 0.7219]],

        [[0.6233, 0.4043, 0.5282],
         [0.0512, 0.2521, 0.3188],
         [0.8695, 0.8867, 0.8121],
         ...,
         [0.2312, 0.9242, 0.3300],
         [0.9708, 0.8952, 0.3714],
         [0.0225, 0.7449, 0.2699]],

        ...,

        [[0.2548, 0.2132, 0.7596],
         [0.4446, 0.2405, 0.4835],
         [0.6449, 0.9974, 0.4527],
         ...,
         [0.1805, 0.2607, 0.7586],
         [0.1826, 0.1307, 0.2494],
         [0.8873, 0.3647, 0.2541]],

        [[0.0743, 0.8209, 0.6273],
         [0.3781, 0.2861, 0.3699],
         [0.

In [66]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [67]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [68]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [69]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [70]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [71]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [72]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [73]:
some_tensor = torch.rand(size=(3,4),dtype=torch.float16)
some_tensor

tensor([[0.1533, 0.1885, 0.6475, 0.0361],
        [0.3696, 0.6348, 0.3965, 0.2490],
        [0.1494, 0.7134, 0.2134, 0.8691]], dtype=torch.float16)

In [74]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1533, 0.1885, 0.6475, 0.0361],
        [0.3696, 0.6348, 0.3965, 0.2490],
        [0.1494, 0.7134, 0.2134, 0.8691]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


In [75]:
#Manipulation of Tensors

tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [76]:
tensor*10


tensor([10, 20, 30])

In [77]:
tensor-10

tensor([-9, -8, -7])

In [78]:
torch.add(tensor,10)

tensor([11, 12, 13])

In [79]:
torch.mul(tensor,20)

tensor([20, 40, 60])

In [80]:
#Element wise Multipllication
print(tensor,'*',tensor)
print(f'Equals: {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [81]:
## Matrix multiplication
%%time
torch.matmul(tensor,tensor)


CPU times: user 64 µs, sys: 10 µs, total: 74 µs
Wall time: 79.4 µs


tensor(14)

In [82]:
## Mulipliction by hand
%%time
value =0
for ele in tensor:
 value+=ele*ele
print(value)

tensor(14)
CPU times: user 1.35 ms, sys: 56 µs, total: 1.41 ms
Wall time: 1.42 ms


In [83]:
MATRIX1 = torch.tensor([[2,3,5],
                        [5,6,7],
                        [9,2,4]])

In [84]:
MATRIX2 = torch.tensor([[9,5,6],
                        [5,3,4],
                        [2,5,6]])

In [85]:
torch.matmul(MATRIX2,MATRIX1)

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [86]:
MATRIX2 @ MATRIX1

tensor([[ 97,  69, 104],
        [ 61,  41,  62],
        [ 83,  48,  69]])

In [87]:
torch.matmul(torch.rand(1,3),torch.rand(3,5))

tensor([[0.9467, 0.6029, 0.8414, 0.9787, 1.2979]])

In [88]:
tensor_1= torch.tensor([[1,2],
                        [4,5],
                        [7,8]])

In [89]:
tensor_2 = torch.tensor([[10,11],
                         [12,13],
                         [14,15]])

In [90]:
tensor_1.shape ,tensor_2.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [92]:
torch.matmul(tensor_1,tensor_2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [93]:
transpose_of_tensor_2 =tensor_2.T
transpose_of_tensor_2

tensor([[10, 12, 14],
        [11, 13, 15]])

In [94]:
transpose_of_tensor_2.shape

torch.Size([2, 3])

In [95]:
torch.matmul(tensor_1,transpose_of_tensor_2)

tensor([[ 32,  38,  44],
        [ 95, 113, 131],
        [158, 188, 218]])

In [96]:
## Here shape of the tensor 1 and 2 are (3,2) and (3,2)
## We Know for multiplication of two matrix of shape (m,n)and (p,q) n=p and the
##Output matrix will be shape (m,q)

In [97]:
print(f"Shape of the tensor_1: {tensor_1.shape} and tensor_2: {tensor_2.shape}")
print(f"Shape of the tensor_1: {tensor_1.shape} and shape of the tensor_2 transpose matrix is : {transpose_of_tensor_2.shape}")
print(f"Shape of the output tensor: {torch.matmul(tensor_1,transpose_of_tensor_2).shape}")


Shape of the tensor_1: torch.Size([3, 2]) and tensor_2: torch.Size([3, 2])
Shape of the tensor_1: torch.Size([3, 2]) and shape of the tensor_2 transpose matrix is : torch.Size([2, 3])
Shape of the output tensor: torch.Size([3, 3])


In [102]:
## Find the min,Max,Sum etc tensor aggregation
x = torch.arange(1 , 100 ,10)
x , x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [99]:
torch.min(x) , x.min()

(tensor(0), tensor(0))

In [100]:
torch.max(x) , x.max()

(tensor(90), tensor(90))

In [106]:
## the torch.mean function required a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()


(tensor(46.), tensor(46.))

In [103]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [104]:
#find the min or max values index position
x.argmin()

tensor(0)

In [105]:
x.argmax()

tensor(9)

**Reshape ,View , Stacking , Squeeze,Unsqueeze, Permute**

In [107]:
#Reshape
x = torch.arange(1.0 , 10.0)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [111]:
x.ndim

1

In [108]:
#add extra dimension
x_reshaped = x.reshape(1,9)
x_reshaped , x_reshaped.shape


(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [112]:
x_reshaped.ndim

2

In [109]:
x_reshaped = x.reshape(9,1)
x_reshaped , x_reshaped.shape


(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [113]:
x_reshaped.ndim

2

In [118]:
#Change the view
z = x.view(1,9)
z ,z.shape,z.ndim

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]), 2)

In [120]:
#Changing  z changes x because they shares the same memory
z[:,0] = 10
z,x

(tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

In [134]:
# Stack tensor on top of each others
x_stacked = torch.stack([x,x,x,x,x],dim=0)
x_stacked

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [137]:
y = torch.arange(10,19)

In [144]:
xy_stacked = torch.stack([x,y,x,y,x],dim=1)
xy_stacked

tensor([[10., 10., 10., 10., 10.],
        [ 2., 11.,  2., 11.,  2.],
        [ 3., 12.,  3., 12.,  3.],
        [ 4., 13.,  4., 13.,  4.],
        [ 5., 14.,  5., 14.,  5.],
        [ 6., 15.,  6., 15.,  6.],
        [ 7., 16.,  7., 16.,  7.],
        [ 8., 17.,  8., 17.,  8.],
        [ 9., 18.,  9., 18.,  9.]])

In [149]:
#torch.squeez remove  all single dimension from a tsrget tensor
k = torch.arange(1,11)
k_reshape = k.reshape(1,10)
k_reshape

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [150]:
k_reshape.shape

torch.Size([1, 10])

In [152]:
k_squeeze = k_reshape.squeeze()

In [155]:
k_squeeze.shape ,k_reshape.shape

(torch.Size([10]), torch.Size([1, 10]))