<a href="https://colab.research.google.com/github/Imran1hp/Deep-Learning-/blob/main/PyTroch_Fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [51]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [52]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [53]:
#SCALER
scaler = torch.tensor(7)
scaler

tensor(7)

In [54]:
scaler.ndim

0

In [55]:
#VECTOR
vector = torch.tensor([7,5,6])
vector

tensor([7, 5, 6])

In [56]:
vector.ndim

1

In [57]:
vector.shape

torch.Size([3])

In [58]:
#MATRIX
MATRIX = torch.tensor([[1,3,4],
                       [2,4,5],
                       [6,7,8]])
MATRIX

tensor([[1, 3, 4],
        [2, 4, 5],
        [6, 7, 8]])

In [59]:
MATRIX.ndim

2

In [60]:
MATRIX.shape

torch.Size([3, 3])

In [61]:
MATRIX[0]

tensor([1, 3, 4])

In [62]:
MATRIX[2]

tensor([6, 7, 8])

In [63]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]],
                       [[5,3,4],
                        [8,1,6],
                        [9,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[5, 3, 4],
         [8, 1, 6],
         [9, 8, 9]]])

In [64]:
TENSOR.ndim


3

In [65]:
TENSOR.shape

torch.Size([2, 3, 3])

In [66]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [67]:
TENSOR[1]

tensor([[5, 3, 4],
        [8, 1, 6],
        [9, 8, 9]])

In [68]:
#Create a random tensor
random_tensor = torch.rand(5,4,3)
random_tensor

tensor([[[0.5457, 0.3542, 0.3954],
         [0.9472, 0.3411, 0.0498],
         [0.5489, 0.9097, 0.1953],
         [0.1911, 0.3225, 0.9364]],

        [[0.3526, 0.1541, 0.5933],
         [0.8127, 0.3028, 0.6824],
         [0.3020, 0.9624, 0.8534],
         [0.8349, 0.0327, 0.1766]],

        [[0.8896, 0.6336, 0.4423],
         [0.6022, 0.6495, 0.4058],
         [0.0159, 0.7646, 0.7207],
         [0.4401, 0.5946, 0.0980]],

        [[0.0418, 0.2984, 0.4459],
         [0.2726, 0.6016, 0.0744],
         [0.3688, 0.9765, 0.2342],
         [0.9957, 0.0623, 0.0287]],

        [[0.7618, 0.1681, 0.7756],
         [0.4151, 0.5042, 0.4137],
         [0.0708, 0.9658, 0.3122],
         [0.0412, 0.5666, 0.9907]]])

In [69]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor

tensor([[[0.8173, 0.9511, 0.6098],
         [0.1883, 0.1014, 0.5656],
         [0.2094, 0.3366, 0.8143],
         ...,
         [0.9690, 0.9444, 0.9170],
         [0.8351, 0.7890, 0.9076],
         [0.2821, 0.4569, 0.4384]],

        [[0.8168, 0.8580, 0.5828],
         [0.6595, 0.2449, 0.7361],
         [0.5275, 0.2552, 0.9191],
         ...,
         [0.4654, 0.4216, 0.4504],
         [0.6396, 0.3358, 0.6422],
         [0.7629, 0.7034, 0.7067]],

        [[0.0751, 0.7752, 0.2166],
         [0.4206, 0.2828, 0.2748],
         [0.6814, 0.7957, 0.1923],
         ...,
         [0.0729, 0.4952, 0.9811],
         [0.6787, 0.0564, 0.3067],
         [0.3034, 0.7471, 0.3116]],

        ...,

        [[0.8017, 0.8006, 0.0196],
         [0.7562, 0.7887, 0.1163],
         [0.8399, 0.9384, 0.4291],
         ...,
         [0.5949, 0.3048, 0.7108],
         [0.2706, 0.8558, 0.8183],
         [0.0829, 0.7172, 0.4867]],

        [[0.1450, 0.4866, 0.6510],
         [0.8185, 0.4334, 0.6236],
         [0.

In [70]:
#crate a tensor of all Zeros
zeros = torch.zeros(size=(3,4))
zeros


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [71]:
#create a tensor of all Ones
Ones = torch.ones(size=(3,4))
Ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [72]:
zeros*Ones

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [84]:
#use torch.arange()

zero_to_thousand = torch.arange(start=0,end=1000, step=10)
zero_to_thousand

tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
        140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270,
        280, 290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410,
        420, 430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550,
        560, 570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690,
        700, 710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830,
        840, 850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970,
        980, 990])

In [83]:
#creagte tensor like
thousand_zeros = torch.zeros_like(input=zero_to_thousand)
thousand_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

In [82]:
thousand_ones = torch.ones_like(input=zero_to_thousand)
thousand_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1])

In [85]:
zeros_to_one = torch.ones_like(input=zeros)
zeros_to_one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])